// Which image this is, as a compile-time constant in every image.
//
// Referenced from std-no-runtime/Std.props, so it runs for the kernel and for
// every app. An image that does not see SharpOS.Generated.ImageInfo did not
// run the image's generators at all.

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Text;

namespace ImageInfo.Generator;

[Generator(LanguageNames.CSharp)]
public sealed class ImageInfoGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterSourceOutput(context.CompilationProvider, static (ctx, compilation) =>
        {
            string name = compilation.AssemblyName ?? "";
            string source =
                "// <auto-generated/> by ImageInfo.Generator.ImageInfoGenerator\n" +
                "namespace SharpOS.Generated\n" +
                "{\n" +
                "    internal static class ImageInfo\n" +
                "    {\n" +
                "        public const string AssemblyName = \"" + name.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\";\n" +
                "    }\n" +
                "}\n";
            ctx.AddSource("ImageInfo.g.cs", SourceText.From(source, Encoding.UTF8));
        });
    }
}
