// Which image this is, as a compile-time constant in every image.
//
// The first generator in the shared project, and deliberately a small one:
// its job is to prove the wiring — that a generator referenced from
// std-no-runtime/Std.props runs for the kernel and for every app — before the
// pipe-message generator, which needs the same reach, is written. An image that
// does not see SharpOS.Generated.ImageInfo did not run it.

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Text;

namespace SharpOS.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class ImageInfoGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterSourceOutput(context.CompilationProvider, static (ctx, compilation) =>
        {
            string name = compilation.AssemblyName ?? "";
            string source =
                "// <auto-generated/> by SharpOS.Generators.ImageInfoGenerator\n" +
                "namespace SharpOS.Generated\n" +
                "{\n" +
                "    internal static class ImageInfo\n" +
                "    {\n" +
                "        public const string AssemblyName = \"" + name.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\";\n" +
                "    }\n" +
                "}\n";
            ctx.AddSource("ImageInfo.g.cs", SourceText.From(source, Encoding.UTF8));
        });
    }
}
