// `dynamic` without reflection (step 193). For every image:
//
//   CallSiteThunks.RegisterGenerated — one thunk per call-site delegate type:
//     it boxes the arguments, gives them with their static types to
//     DynamicRuntime.Run and unboxes the result; CallSite<T>.Create finds it
//     by T. `Generated` lists the delegate types by metadata name, for the IL
//     check after compilation (Dynamic.Check).
//   DynamicMembers.RegisterGenerated — what a name used at a call site may
//     reach: fields and properties, methods (closed generic instances where a
//     call site names the type arguments), indexers, constructors of types
//     made with `new` over dynamic arguments, delegate Invoke, user-defined
//     operators and conversions where the operations occur; members of
//     anonymous types through a witness; the names of types for messages and
//     the underlying types of nullables.
//
// Members: public and internal of this assembly, in every type it can name
// (its own types, their bases and interfaces, closed generic instances it
// mentions or lists in [assembly: DynamicTypes(…)]). A virtual member is
// written once, at the type that declared it; the call is virtual.

using System.Collections.Generic;
using System.Collections.Immutable;
using System.Globalization;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace SharpOS.Generators.Dynamic;

[Generator(LanguageNames.CSharp)]
public sealed class DynamicGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
        => context.RegisterSourceOutput(context.CompilationProvider, static (ctx, c) => Emit(ctx, c));

    private static void Emit(SourceProductionContext ctx, Compilation c)
    {
        if (c.GetTypeByMetadataName("SharpOS.Std.Dynamic.DynamicRuntime") == null) return;
        var sites = new DynamicSites(c);
        sites.Collect();
        if (!sites.Any) return;
        var e = new Emitter(c, sites);
        ctx.AddSource("CallSiteThunks.g.cs", SourceText.From(e.Thunks(), Encoding.UTF8));
        ctx.AddSource("DynamicMembers.g.cs", SourceText.From(e.Members(), Encoding.UTF8));
    }
}

internal sealed class Emitter
{
    private const string Rt = "global::SharpOS.Std.Dynamic.";
    private readonly Compilation _c;
    private readonly DynamicSites _s;
    private readonly HashSet<ITypeSymbol> _named = new(SymbolEqualityComparer.Default);
    private readonly HashSet<ITypeSymbol> _nullables = new(SymbolEqualityComparer.Default);

    public Emitter(Compilation c, DynamicSites s)
    {
        _c = c;
        _s = s;
    }

    private static string R(ITypeSymbol t) => DynTypes.Render(t);

    private static string Header =>
        "// <auto-generated/> SharpOS Dynamic.Generator\n#nullable disable\n#pragma warning disable\nnamespace SharpOS.Std.Dynamic\n{\n";

    // ---- thunks ----

    public string Thunks()
    {
        var sb = new StringBuilder(Header);
        sb.Append("    public static partial class CallSiteThunks\n    {\n");
        var sigs = _s.Thunks.Values.OrderBy(x => x.Key, System.StringComparer.Ordinal).ToList();
        sb.Append("        internal const string Generated = \"")
          .Append(string.Join("\\n", sigs.Select(MetaDelegate))).Append("\";\n\n");
        var register = new StringBuilder();
        var bodies = new StringBuilder();
        int k = 0;
        foreach (Sig sig in sigs)
        {
            if (!sig.Params.All(t => Thunkable(t)) || (sig.Result != null && !DynTypes.Boxable(_c, sig.Result) && sig.Result.SpecialType != SpecialType.System_Object))
            {
                k++;
                continue;   // the analyzer reports it (SOSD005); the IL check names it
            }
            EmitThunk(sig, k++, register, bodies);
        }
        sb.Append(Chunked(register.ToString(), "__RT"));
        sb.Append(bodies);
        sb.Append("    }\n}\n");
        return sb.ToString();
    }

    private bool Thunkable(ITypeSymbol t)
        => (t is INamedTypeSymbol n && n.IsAnonymousType) || DynTypes.Boxable(_c, t);

    private static string MetaDelegate(Sig sig)
    {
        var all = new List<string> { "System.Runtime.CompilerServices.CallSite" };
        all.AddRange(sig.Params.Select(DynTypes.MetaName));
        if (sig.Result != null) all.Add(DynTypes.MetaName(sig.Result));
        string head = sig.Result == null ? "System.Action`" + all.Count : "System.Func`" + all.Count;
        return head + "<" + string.Join(",", all) + ">";
    }

    private static bool IsAnon(ITypeSymbol t) => t is INamedTypeSymbol n && n.IsAnonymousType;

    private void EmitThunk(Sig sig, int k, StringBuilder register, StringBuilder bodies)
    {
        string name = "__T" + k.ToString(CultureInfo.InvariantCulture);
        string types = "__TT" + k.ToString(CultureInfo.InvariantCulture);
        var parameters = new List<string> { "global::System.Runtime.CompilerServices.CallSite __s" };
        var boxes = new List<string>();
        var typeofs = new List<string>();
        for (int i = 0; i < sig.Params.Length; i++)
        {
            ITypeSymbol t = sig.Params[i];
            string a = "a" + i.ToString(CultureInfo.InvariantCulture);
            if (IsAnon(t))
            {
                parameters.Add("object " + a);
                boxes.Add(a);
                typeofs.Add("typeof(object)");
                continue;
            }
            parameters.Add(R(t) + " " + a);
            boxes.Add(Box(t, a));
            typeofs.Add("typeof(" + R(t) + ")");
            NoteType(t);
        }
        string ret = sig.Result == null ? "void" : R(sig.Result);
        if (sig.Result != null) NoteType(sig.Result);
        bodies.Append("        private static global::System.Type[] ").Append(types).Append(";\n");
        bodies.Append("        private static ").Append(ret).Append(' ').Append(name).Append('(').Append(string.Join(", ", parameters)).Append(")\n        {\n");
        string call = Rt + "DynamicRuntime.Run(__s, new object[] { " + string.Join(", ", boxes) + " }, "
                      + types + " ??= new global::System.Type[] { " + string.Join(", ", typeofs) + " })";
        if (sig.Result == null) bodies.Append("            ").Append(call).Append(";\n");
        else bodies.Append("            object __r = ").Append(call).Append(";\n            return ").Append(Unbox(sig.Result, "__r")).Append(";\n");
        bodies.Append("        }\n\n");

        // The delegate type, with each anonymous type standing as a generic parameter
        // bound by a witness: generated code cannot name an anonymous type.
        var delegateArgs = new List<string> { "global::System.Runtime.CompilerServices.CallSite" };
        var generic = new List<string>();
        var witnesses = new List<string>();
        foreach (ITypeSymbol t in sig.Params)
        {
            if (IsAnon(t))
            {
                string g = "X" + generic.Count.ToString(CultureInfo.InvariantCulture);
                generic.Add(g);
                witnesses.Add(Witness(t) ?? "null");
                delegateArgs.Add(g);
            }
            else delegateArgs.Add(R(t));
        }
        if (sig.Result != null) delegateArgs.Add(R(sig.Result));
        string delegateType = (sig.Result == null ? "global::System.Action<" : "global::System.Func<") + string.Join(", ", delegateArgs) + ">";
        if (generic.Count == 0)
        {
            register.Append("            Register(typeof(").Append(delegateType).Append("), new ").Append(delegateType)
                    .Append('(').Append(name).Append("));\n");
            return;
        }
        if (witnesses.Contains("null")) return;
        string reg = "__R" + k.ToString(CultureInfo.InvariantCulture);
        register.Append("            ").Append(reg).Append('(').Append(string.Join(", ", witnesses)).Append(");\n");
        bodies.Append("        private static void ").Append(reg).Append('<').Append(string.Join(", ", generic)).Append(">(")
              .Append(string.Join(", ", generic.Select(g => g + " w" + g))).Append(")")
              .Append(string.Concat(generic.Select(g => " where " + g + " : class")))
              .Append("\n            => Register(typeof(").Append(delegateType).Append("), new ").Append(delegateType)
              .Append('(').Append(name).Append("));\n\n");
    }

    private string Box(ITypeSymbol t, string expr)
    {
        if (DynTypes.NullableUnderlying(t) != null) return Rt + "DynamicBox.OfNullable(" + expr + ")";
        return t.IsValueType ? "(object)" + expr : expr;
    }

    private string Unbox(ITypeSymbol t, string expr)
    {
        if (t.SpecialType == SpecialType.System_Object) return expr;
        ITypeSymbol? under = DynTypes.NullableUnderlying(t);
        if (under != null) return Rt + "DynamicBox.ToNullable<" + R(under) + ">(" + expr + ")";
        return "(" + R(t) + ")" + expr;
    }

    private void NoteType(ITypeSymbol t)
    {
        if (DynTypes.Nameable(_c, t)) _named.Add(t);
        if (DynTypes.NullableUnderlying(t) != null) _nullables.Add(t);
    }

    // A value of an anonymous type's exact type: anonymous types with the same
    // names, types and order are one type in an assembly.
    private string? Witness(ITypeSymbol t)
    {
        if (t is INamedTypeSymbol n && n.IsAnonymousType)
        {
            var parts = new List<string>();
            foreach (IPropertySymbol p in n.GetMembers().OfType<IPropertySymbol>())
            {
                string? w = Witness(p.Type);
                if (w == null) return null;
                parts.Add(p.Name + " = " + w);
            }
            return "new { " + string.Join(", ", parts) + " }";
        }
        return DynTypes.Nameable(_c, t) ? "default(" + R(t) + ")" : null;
    }

    // ---- members ----

    private HashSet<INamedTypeSymbol> Universe()
    {
        var u = new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default);
        void Add(INamedTypeSymbol? t)
        {
            if (t == null || !Usable(t) || !u.Add(t)) return;
            Add(t.BaseType);
            foreach (INamedTypeSymbol i in t.Interfaces) Add(i);
        }
        void Walk(INamespaceOrTypeSymbol ns)
        {
            foreach (INamespaceOrTypeSymbol m in ns.GetMembers().OfType<INamespaceOrTypeSymbol>())
            {
                if (m is INamedTypeSymbol t)
                {
                    if (!t.IsGenericType) Add(t);
                    Walk(t);
                }
                else Walk(m);
            }
        }
        Walk(_c.Assembly.GlobalNamespace);
        foreach (INamedTypeSymbol g in _s.SeenGenerics) Add(g);
        foreach (ITypeSymbol t in _named) if (t is INamedTypeSymbol n) Add(n);
        foreach (Sig sig in _s.Thunks.Values)
            foreach (ITypeSymbol t in sig.Params.Concat(sig.Result == null ? new ITypeSymbol[0] : new[] { sig.Result }))
                if (t is INamedTypeSymbol n) Add(n);
        foreach (ITypeSymbol t in _s.Constructed) if (t is INamedTypeSymbol n) Add(n);
        foreach (ITypeSymbol t in _s.ConvertTargets) if (t is INamedTypeSymbol n) Add(n);
        foreach (AttributeData a in _c.Assembly.GetAttributes())
            if (a.AttributeClass?.ToDisplayString() == "SharpOS.Std.Dynamic.DynamicTypesAttribute")
                foreach (TypedConstant arg in a.ConstructorArguments)
                    foreach (TypedConstant v in arg.Kind == TypedConstantKind.Array ? arg.Values : ImmutableArray.Create(arg))
                        if (v.Value is INamedTypeSymbol n) Add(n);
        return u;
    }

    private bool Usable(INamedTypeSymbol t)
        => DynTypes.Nameable(_c, t) && !t.IsRefLikeType && !t.IsUnboundGenericType
           && t.OriginalDefinition.SpecialType != SpecialType.System_Nullable_T   // a boxed T? is a boxed T
           && !(t.IsGenericType && t.TypeArguments.Any(DynTypes.ContainsTypeParameter));

    // Static abstract or virtual interface members are reached only through a
    // type parameter; explicit implementations not by name at all.
    private bool Accessible(ISymbol s)
        => _c.IsSymbolAccessibleWithin(s, _c.Assembly)
           && !(s.IsStatic && (s.IsAbstract || s.IsVirtual) && s.ContainingType?.TypeKind == TypeKind.Interface)
           && !(s is IMethodSymbol m && m.ExplicitInterfaceImplementations.Length > 0)
           && !(s is IPropertySymbol p && p.ExplicitInterfaceImplementations.Length > 0);

    public string Members()
    {
        var sb = new StringBuilder(Header);
        sb.Append("    public static partial class DynamicMembers\n    {\n");
        var body = new StringBuilder();
        HashSet<INamedTypeSymbol> universe = Universe();
        var names = new HashSet<string>(_s.MemberNames);
        names.UnionWith(_s.MethodNames);
        var delegates = new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default);

        foreach (INamedTypeSymbol t in universe.OrderBy(x => x.ToDisplayString(), System.StringComparer.Ordinal))
        {
            foreach (string name in names.OrderBy(x => x, System.StringComparer.Ordinal))
                foreach (ISymbol m in t.GetMembers(name))
                {
                    if (m is IFieldSymbol f) FieldOrProperty(body, t, f.Name, f.Type, f.IsStatic, Accessible(f), !f.IsReadOnly && !f.IsConst && Accessible(f), f.IsImplicitlyDeclared, delegates);
                    else if (m is IPropertySymbol p && !p.IsIndexer && !p.IsOverride)
                        FieldOrProperty(body, t, p.Name, p.Type, p.IsStatic,
                                        p.GetMethod != null && Accessible(p.GetMethod),
                                        p.SetMethod != null && !p.SetMethod.IsInitOnly && Accessible(p.SetMethod), false, delegates);
                    else if (m is IMethodSymbol method && _s.MethodNames.Contains(name) && method.MethodKind == MethodKind.Ordinary)
                        Method(body, t, method);
                }
            if (_s.Index)
                foreach (IPropertySymbol ix in t.GetMembers().OfType<IPropertySymbol>().Where(p => p.IsIndexer && !p.IsOverride))
                    Indexer(body, t, ix);
            if (t.TypeKind == TypeKind.Delegate && _s.Invoke) delegates.Add(t);
            foreach (IMethodSymbol op in t.GetMembers().OfType<IMethodSymbol>())
            {
                if (op.MethodKind == MethodKind.UserDefinedOperator && _s.Operators.Contains(op.Name)) Operator(body, t, op);
                else if (op.MethodKind == MethodKind.Conversion
                         && (_s.ConvertTargets.Contains(DynTypes.Normalize(_c, op.ReturnType))
                             || (_s.IsTrue && op.ReturnType.SpecialType == SpecialType.System_Boolean)))
                    Conversion(body, t, op);
            }
        }
        foreach (ITypeSymbol t in _s.Constructed)
            if (t is INamedTypeSymbol n && Usable(n) && !n.IsAbstract)
                foreach (IMethodSymbol ctor in n.InstanceConstructors) Constructor(body, n, ctor);
        foreach (INamedTypeSymbol d in delegates) Invoke(body, d);
        foreach (INamedTypeSymbol a in _s.Anonymous) Anonymous(body, a, names);

        // Names for messages: every type the tables or call sites mention, and the image's own.
        foreach (INamedTypeSymbol t in universe)
            if (!IsStd(t)) _named.Add(t);
        foreach (ITypeSymbol t in _named.OrderBy(x => x.ToDisplayString(), System.StringComparer.Ordinal))
            if (DynTypes.Nameable(_c, t) && t.SpecialType == SpecialType.None)
                body.Append("            Name(typeof(").Append(R(t)).Append("), ").Append(Literal(t.ToDisplayString())).Append(");\n");
        foreach (ITypeSymbol t in _nullables)
            body.Append("            Nullable(typeof(").Append(R(t)).Append("), typeof(").Append(R(DynTypes.NullableUnderlying(t)!)).Append("));\n");

        sb.Append(Chunked(body.ToString(), "__RM")).Append("    }\n}\n");
        return sb.ToString();
    }

    // RegisterGenerated calling methods of a few registrations each. One method
    // with them all had 4780 GC slots in its frame under ILC (a type object, an
    // array and a delegate per line), and the kernel's stack walk decodes at most
    // 4096: the frame's roots were lost under GC stress (step 193).
    private const int ChunkSize = 24;

    private static string Chunked(string statements, string prefix)
    {
        string[] lines = statements.Split(new[] { '\n' }, System.StringSplitOptions.RemoveEmptyEntries);
        var calls = new StringBuilder();
        var methods = new StringBuilder();
        for (int i = 0, n = 0; i < lines.Length; i += ChunkSize, n++)
        {
            string name = prefix + n.ToString(CultureInfo.InvariantCulture);
            calls.Append("            ").Append(name).Append("();\n");
            methods.Append("        private static void ").Append(name).Append("()\n        {\n");
            for (int j = i; j < lines.Length && j < i + ChunkSize; j++) methods.Append(lines[j]).Append('\n');
            methods.Append("        }\n\n");
        }
        return "        static partial void RegisterGenerated()\n        {\n" + calls + "        }\n\n" + methods;
    }

    private static bool IsStd(INamedTypeSymbol t)
        => t.DeclaringSyntaxReferences.All(r => r.SyntaxTree.FilePath.Replace('\\', '/').Contains("/std-no-runtime/")
                                                 || r.SyntaxTree.FilePath.Replace('\\', '/').Contains("/sdk/"));

    private static string Literal(string s)
        => "\"" + s.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";

    private string TypeOf(ITypeSymbol t)
    {
        NoteType(t);
        return "typeof(" + R(t) + ")";
    }

    // The receiver as the member is reached: a class or interface by cast, a struct in its box.
    private string Receiver(INamedTypeSymbol owner, bool isStatic)
    {
        if (isStatic) return R(owner);
        if (owner.IsValueType) return Rt + "DynamicBox.Ref<" + R(owner) + ">(__o)";
        return "((" + R(owner) + ")__o)";
    }

    private string Convert(ITypeSymbol t, string expr)
    {
        if (t.SpecialType == SpecialType.System_Object) return expr;
        return Unbox(t, expr);
    }

    private string ToObject(ITypeSymbol t, string expr)
    {
        if (DynTypes.NullableUnderlying(t) != null) return Rt + "DynamicBox.OfNullable(" + expr + ")";
        return "(object)(" + expr + ")";
    }

    private void FieldOrProperty(StringBuilder sb, INamedTypeSymbol owner, string name, ITypeSymbol type, bool isStatic,
                                 bool canGet, bool canSet, bool implicitDecl, HashSet<INamedTypeSymbol> delegates)
    {
        if (implicitDecl || (!canGet && !canSet) || !DynTypes.Boxable(_c, type)) return;
        if (owner.IsStatic && !isStatic) return;
        string recv = Receiver(owner, isStatic);
        string get = canGet ? "static __o => " + ToObject(type, recv + "." + Esc(name)) : "null";
        string set = canSet ? "static (__o, __v) => " + recv + "." + Esc(name) + " = " + Convert(type, "__v") : "null";
        sb.Append("            Member(").Append(TypeOf(owner)).Append(", ").Append(Literal(name)).Append(", ").Append(TypeOf(type))
          .Append(", ").Append(isStatic ? "true" : "false").Append(", ").Append(get).Append(", ").Append(set).Append(");\n");
        if (type is INamedTypeSymbol d && d.TypeKind == TypeKind.Delegate && Usable(d)) delegates.Add(d);
    }

    private static string Esc(string name)
        => Microsoft.CodeAnalysis.CSharp.SyntaxFacts.GetKeywordKind(name) != Microsoft.CodeAnalysis.CSharp.SyntaxKind.None ? "@" + name : name;

    private bool ParametersUsable(IMethodSymbol m)
        => m.Parameters.All(p => (p.RefKind == RefKind.None || p.RefKind == RefKind.In) && DynTypes.Boxable(_c, p.Type)
                                 && (!p.IsParams || p.Type is IArrayTypeSymbol));

    private bool ReturnUsable(IMethodSymbol m) => m.ReturnsVoid || DynTypes.Boxable(_c, m.ReturnType);

    // Arguments of a generated invoker: a[i] as the parameter's type, a default when left out,
    // the typed array of an expanded params call.
    private string Arguments(IMethodSymbol m, StringBuilder prologue)
    {
        var args = new List<string>();
        for (int i = 0; i < m.Parameters.Length; i++)
        {
            IParameterSymbol p = m.Parameters[i];
            string a = "__a[" + i.ToString(CultureInfo.InvariantCulture) + "]";
            if (p.IsParams && p.Type is IArrayTypeSymbol arr)
            {
                string e = R(arr.ElementType);
                string v = "__p" + i.ToString(CultureInfo.InvariantCulture);
                prologue.Append(e).Append("[] ").Append(v).Append("; if (").Append(a).Append(" is ").Append(Rt).Append("ParamsPack __k) { ")
                        .Append(v).Append(" = new ").Append(e).Append("[__k.Items.Length]; for (int __i = 0; __i < __k.Items.Length; __i++) ")
                        .Append(v).Append("[__i] = ").Append(Convert(arr.ElementType, "__k.Items[__i]")).Append("; } else ")
                        .Append(v).Append(" = (").Append(R(p.Type)).Append(")").Append(a).Append("; ");
                args.Add(v);
                continue;
            }
            string value = Convert(p.Type, a);
            if (p.HasExplicitDefaultValue)
                value = "(object.ReferenceEquals(" + a + ", " + Rt + "DynamicMethod.Missing) ? " + Default(p) + " : " + value + ")";
            args.Add(value);
        }
        return string.Join(", ", args);
    }

    private string Default(IParameterSymbol p)
    {
        object? v = p.ExplicitDefaultValue;
        string type = R(p.Type);
        switch (v)
        {
            case null: return "default(" + type + ")";
            case string s: return Literal(s);
            case bool b: return b ? "true" : "false";
            case char ch: return "(" + type + ")" + ((int)ch).ToString(CultureInfo.InvariantCulture);
            case float f: return "(" + type + ")" + f.ToString("R", CultureInfo.InvariantCulture) + "f";
            case double d: return "(" + type + ")" + d.ToString("R", CultureInfo.InvariantCulture) + "d";
            case decimal m: return "(" + type + ")" + m.ToString(CultureInfo.InvariantCulture) + "m";
            case ulong ul: return "(" + type + ")" + ul.ToString(CultureInfo.InvariantCulture) + "UL";
            case long l: return "(" + type + ")(" + l.ToString(CultureInfo.InvariantCulture) + "L)";
            default: return "(" + type + ")(" + System.Convert.ToString(v, CultureInfo.InvariantCulture) + ")";
        }
    }

    private static int Required(IMethodSymbol m) => m.Parameters.Count(p => !p.HasExplicitDefaultValue && !p.IsParams);

    private string ParamTypes(IMethodSymbol m, out string paramsElement)
    {
        paramsElement = "null";
        if (m.Parameters.Length > 0 && m.Parameters[m.Parameters.Length - 1].IsParams
            && m.Parameters[m.Parameters.Length - 1].Type is IArrayTypeSymbol arr)
            paramsElement = TypeOf(arr.ElementType);
        return "new global::System.Type[] { " + string.Join(", ", m.Parameters.Select(p => TypeOf(p.Type))) + " }";
    }

    private string Invoker(IMethodSymbol m, string call)
    {
        var prologue = new StringBuilder();
        string args = Arguments(m, prologue);
        string invocation = call + "(" + args + ")";
        if (m.ReturnsVoid) return "static (__o, __a) => { " + prologue + invocation + "; return null; }";
        return "static (__o, __a) => { " + prologue + "return " + ToObject(m.ReturnType, invocation) + "; }";
    }

    private void Method(StringBuilder sb, INamedTypeSymbol owner, IMethodSymbol m)
    {
        if (m.IsOverride || !Accessible(m)) return;
        if (owner.IsStatic && !m.IsStatic) return;
        string recv = Receiver(owner, m.IsStatic);
        // A generic method is judged by its instances: the definition's T is never nameable.
        if (m.IsGenericMethod)
        {
            bool closed = false;
            foreach (var call in _s.GenericCalls.Where(g => g.Name == m.Name && g.TypeArguments.Length == m.TypeParameters.Length))
            {
                if (!call.TypeArguments.All(a => DynTypes.Nameable(_c, a))) continue;
                IMethodSymbol inst;
                try { inst = m.Construct(call.TypeArguments.Select(a => DynTypes.Normalize(_c, a)).ToArray()); }
                catch { continue; }
                if (!SatisfiesConstraints(m, inst) || !ParametersUsable(inst) || !ReturnUsable(inst)) continue;
                string targs = string.Join(", ", inst.TypeArguments.Select(R));
                string ptypes = ParamTypes(inst, out string pe);
                sb.Append("            Generic(").Append(TypeOf(owner)).Append(", ").Append(Literal(m.Name)).Append(", ")
                  .Append(m.IsStatic ? "true" : "false").Append(", new global::System.Type[] { ")
                  .Append(string.Join(", ", inst.TypeArguments.Select(TypeOf))).Append(" }, ").Append(ptypes).Append(", ").Append(pe)
                  .Append(", ").Append(inst.ReturnsVoid ? "null" : TypeOf(inst.ReturnType)).Append(", ")
                  .Append(Required(inst).ToString(CultureInfo.InvariantCulture)).Append(", ")
                  .Append(Invoker(inst, recv + "." + Esc(m.Name) + "<" + targs + ">")).Append(");\n");
                closed = true;
            }
            if (!closed)
                sb.Append("            NeedsInference(").Append(TypeOf(owner)).Append(", ").Append(Literal(m.Name)).Append(", ")
                  .Append(m.IsStatic ? "true" : "false").Append(", ").Append(m.TypeParameters.Length.ToString(CultureInfo.InvariantCulture)).Append(");\n");
            return;
        }
        if (!ParametersUsable(m) || !ReturnUsable(m)) return;
        string types = ParamTypes(m, out string paramsElement);
        sb.Append("            Method(").Append(TypeOf(owner)).Append(", ").Append(Literal(m.Name)).Append(", ")
          .Append(m.IsStatic ? "true" : "false").Append(", ").Append(types).Append(", ").Append(paramsElement).Append(", ")
          .Append(m.ReturnsVoid ? "null" : TypeOf(m.ReturnType)).Append(", ").Append(Required(m).ToString(CultureInfo.InvariantCulture))
          .Append(", ").Append(Invoker(m, recv + "." + Esc(m.Name))).Append(");\n");
    }

    private bool SatisfiesConstraints(IMethodSymbol definition, IMethodSymbol inst)
    {
        for (int i = 0; i < definition.TypeParameters.Length; i++)
        {
            ITypeParameterSymbol p = definition.TypeParameters[i];
            ITypeSymbol a = inst.TypeArguments[i];
            if (p.HasValueTypeConstraint && !a.IsValueType) return false;
            if (p.HasReferenceTypeConstraint && !a.IsReferenceType) return false;
            if (p.HasUnmanagedTypeConstraint && !a.IsUnmanagedType) return false;
            foreach (ITypeSymbol c in p.ConstraintTypes)
                if (!DynTypes.ContainsTypeParameter(c) && !_c.HasImplicitConversion(a, c)) return false;
        }
        return true;
    }

    private void Indexer(StringBuilder sb, INamedTypeSymbol owner, IPropertySymbol ix)
    {
        if (!DynTypes.Boxable(_c, ix.Type) || owner.IsStatic) return;
        if (!ix.Parameters.All(p => (p.RefKind == RefKind.None || p.RefKind == RefKind.In) && DynTypes.Boxable(_c, p.Type))) return;
        string recv = Receiver(owner, false);
        if (ix.GetMethod != null && Accessible(ix.GetMethod))
        {
            IMethodSymbol g = ix.GetMethod;
            var prologue = new StringBuilder();
            string args = Arguments(g, prologue);
            string types = ParamTypes(g, out string pe);
            sb.Append("            Method(").Append(TypeOf(owner)).Append(", \"get_Item\", false, ").Append(types).Append(", ").Append(pe)
              .Append(", ").Append(TypeOf(ix.Type)).Append(", ").Append(Required(g).ToString(CultureInfo.InvariantCulture))
              .Append(", static (__o, __a) => { ").Append(prologue).Append("return ").Append(ToObject(ix.Type, recv + "[" + args + "]")).Append("; });\n");
        }
        if (ix.SetMethod != null && Accessible(ix.SetMethod) && !ix.SetMethod.IsInitOnly)
        {
            IMethodSymbol s = ix.SetMethod;
            int n = s.Parameters.Length - 1;
            var prologue = new StringBuilder();
            var idx = new List<string>();
            for (int i = 0; i < n; i++)
                idx.Add(Convert(s.Parameters[i].Type, "__a[" + i.ToString(CultureInfo.InvariantCulture) + "]"));
            string types = "new global::System.Type[] { " + string.Join(", ", s.Parameters.Select(p => TypeOf(p.Type))) + " }";
            sb.Append("            Method(").Append(TypeOf(owner)).Append(", \"set_Item\", false, ").Append(types).Append(", null, null, ")
              .Append(s.Parameters.Length.ToString(CultureInfo.InvariantCulture))
              .Append(", static (__o, __a) => { ").Append(recv).Append('[').Append(string.Join(", ", idx)).Append("] = ")
              .Append(Convert(ix.Type, "__a[" + n.ToString(CultureInfo.InvariantCulture) + "]")).Append("; return null; });\n");
        }
    }

    private void Constructor(StringBuilder sb, INamedTypeSymbol owner, IMethodSymbol ctor)
    {
        if (!Accessible(ctor) || !ParametersUsable(ctor)) return;
        string types = ParamTypes(ctor, out string pe);
        var prologue = new StringBuilder();
        string args = Arguments(ctor, prologue);
        sb.Append("            Method(").Append(TypeOf(owner)).Append(", \".ctor\", true, ").Append(types).Append(", ").Append(pe)
          .Append(", ").Append(TypeOf(owner)).Append(", ").Append(Required(ctor).ToString(CultureInfo.InvariantCulture))
          .Append(", static (__o, __a) => { ").Append(prologue).Append("return (object)new ").Append(R(owner)).Append('(').Append(args).Append("); });\n");
    }

    private void Invoke(StringBuilder sb, INamedTypeSymbol d)
    {
        IMethodSymbol? m = d.DelegateInvokeMethod;
        if (m == null || !ParametersUsable(m) || !ReturnUsable(m) || !Usable(d)) return;
        string types = ParamTypes(m, out string pe);
        sb.Append("            Method(").Append(TypeOf(d)).Append(", \"Invoke\", false, ").Append(types).Append(", ").Append(pe)
          .Append(", ").Append(m.ReturnsVoid ? "null" : TypeOf(m.ReturnType)).Append(", ").Append(Required(m).ToString(CultureInfo.InvariantCulture))
          .Append(", ").Append(Invoker(m, "((" + R(d) + ")__o)")).Append(");\n");
    }

    private void Operator(StringBuilder sb, INamedTypeSymbol owner, IMethodSymbol op)
    {
        if (!Accessible(op) || !ParametersUsable(op) || !ReturnUsable(op)) return;
        string types = ParamTypes(op, out _);
        string a0 = Convert(op.Parameters[0].Type, "__a[0]");
        string expr;
        string? symbol = DynTypes.OperatorSyntax(op.Name);
        if (op.Parameters.Length == 2 && symbol != null)
            expr = "(" + a0 + ") " + symbol + " (" + Convert(op.Parameters[1].Type, "__a[1]") + ")";
        else if (op.Parameters.Length == 1 && symbol != null)
            expr = symbol + "(" + a0 + ")";
        else if (op.Name == "op_True") expr = "(" + a0 + ") ? true : false";
        else if (op.Name == "op_False") expr = "(" + a0 + ") ? false : true";
        else if (op.Name == "op_Increment" || op.Name == "op_Decrement")
        {
            string step = op.Name == "op_Increment" ? "++" : "--";
            sb.Append("            Method(").Append(TypeOf(owner)).Append(", ").Append(Literal(op.Name)).Append(", true, ").Append(types)
              .Append(", null, ").Append(TypeOf(op.ReturnType)).Append(", 1, static (__o, __a) => { var __x = ").Append(a0).Append("; __x")
              .Append(step).Append("; return ").Append(ToObject(op.ReturnType, "__x")).Append("; });\n");
            return;
        }
        else return;
        sb.Append("            Method(").Append(TypeOf(owner)).Append(", ").Append(Literal(op.Name)).Append(", true, ").Append(types)
          .Append(", null, ").Append(TypeOf(op.ReturnType)).Append(", ").Append(op.Parameters.Length.ToString(CultureInfo.InvariantCulture))
          .Append(", static (__o, __a) => ").Append(ToObject(op.ReturnType, expr)).Append(");\n");
    }

    private void Conversion(StringBuilder sb, INamedTypeSymbol owner, IMethodSymbol op)
    {
        if (!Accessible(op) || !ParametersUsable(op) || !ReturnUsable(op)) return;
        string types = ParamTypes(op, out _);
        string expr = "(" + R(op.ReturnType) + ")(" + Convert(op.Parameters[0].Type, "__a[0]") + ")";
        sb.Append("            Method(").Append(TypeOf(owner)).Append(", ").Append(Literal(op.Name)).Append(", true, ").Append(types)
          .Append(", null, ").Append(TypeOf(op.ReturnType)).Append(", 1, static (__o, __a) => ").Append(ToObject(op.ReturnType, expr)).Append(");\n");
    }

    private void Anonymous(StringBuilder sb, INamedTypeSymbol a, HashSet<string> names)
    {
        string? witness = Witness(a);
        if (witness == null) return;
        foreach (IPropertySymbol p in a.GetMembers().OfType<IPropertySymbol>())
        {
            if (!names.Contains(p.Name)) continue;
            string type = DynTypes.Nameable(_c, p.Type) ? TypeOf(p.Type) : "typeof(object)";
            sb.Append("            Anonymous(").Append(witness).Append(", ").Append(Literal(p.Name)).Append(", ").Append(type)
              .Append(", static __x => ").Append(DynTypes.Nameable(_c, p.Type) ? ToObject(p.Type, "__x." + p.Name) : "(object)__x." + p.Name).Append(");\n");
        }
    }
}
